### ISSUE TITLE
`cj state` note working

### ISSUE THREAD

**Issue by xyhan-github** [monajemi/clusterjob#22]
Hi Hatef,

`cj state` stopped working for all my jobs. In particular, this happens

```

Xiaoyan$ cj state 88af1ee2a2a52947fe11762b8c948fc29c87677a --v
sacct: error: slurmdbd: Too wide of a date range in query
pid 88af1ee2a2a52947fe11762b8c948fc29c87677a
remote_account: xiaoyanh@login.sherlock.stanford.edu
1         12278820            Unknown   
2         12278821            Unknown   
3         12278822            Unknown   
4         12278824            Unknown   
5         12278825            Unknown   
6         12278827            Unknown   
7         12278828            Unknown   
8         12278829            Unknown   

```

As you can see I get a `sacct: error: slurmdbd: Too wide of a date range in query` error and all my jobs are listed as `Unknown`. Do you know what might be happening?

**Comment by monajemi** [comment]
Hi Xiaoyan, 

Do you only have 8 jobs in 88af1ee2a2 ?
Sometimes when you have a large number of jobs, Slurm gives some errors.
If not, you should contact Sherlock if this problem continues. It seems its a Sherlock error.

Hatef
